### ISSUE TITLE
Nuclei Toolchain 2023.10 failed to disable V-ext autovectorization 

### ISSUE THREAD

**Issue by bigmagic123** [riscv-mcu/riscv-gnu-toolchain#13]
When using the rvv extension compiler, if you do not enable rvv automatic vectorization, there is still a chance that rvv instructions will be generated.

![image](https://github.com/riscv-mcu/riscv-gnu-toolchain/assets/57786250/449b5e1c-553f-4575-8686-a737d3e5c16f)

**Comment by bigmagic123** [comment]
For more detailed information, please refer to the link

1. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112538
2. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112537

**Comment by fanghuaqi** [comment]
And from `2024.06` release, `-mmemcpy-strategy=` option in 2023.10 changed to `-mstringop-strategy=` in 2024.06, see https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=3dc7947e5d766ed2f30c9aa8286b36f9287a1d80, and Nuclei SDK also changed this option, see https://github.com/Nuclei-Software/nuclei-sdk/commit/a487143e9d09757ef2613fee10440f5dc00bfb36
