### ISSUE TITLE
how to track and fix bug about the risc-v gcc 

### ISSUE THREAD

**Issue by NZtechpapa** [riscv-mcu/riscv-gnu-toolchain#20]
1. can you share some documents  about   how to develop    nuclei  gcc 
2.  meet some compiler issue , want to track and fix the issue.  can you share some documents about how to track gcc codes?

**Comment by fanghuaqi** [comment]
see https://github.com/riscv-mcu/riscv-gnu-toolchain/tree/nuclei/2024/scripts/toolchain#readme for how to build toolchain.

For gcc related issues, please ask it here https://github.com/riscv-collab/riscv-gnu-toolchain/issues or https://gcc.gnu.org/bugzilla/
