### ISSUE TITLE
can't download the prebuilt toolchain

### ISSUE THREAD

**Issue by 4305sir** [riscv-mcu/riscv-gnu-toolchain#21]
![image](https://github.com/user-attachments/assets/327eb67d-9450-4a4b-afd8-5b55e5851e96)

**Comment by fanghuaqi** [comment]
Fixed now, you can try https://download.nucleisys.com/upload/files/toolchain/gcc/nuclei_riscv_newlibc_prebuilt_linux64_2024.06.tar.bz2
