### ISSUE TITLE
 does toolchain don't support  info files  on gdb?

### ISSUE THREAD

**Issue by 4305sir** [riscv-mcu/riscv-gnu-toolchain#22]
info files  the gdb says:
Remote target using gdb-specific protocol:

and it's why there is no debug symbol on demo helloworld project elf

**Comment by fanghuaqi** [comment]
@4305sir Did you compile your application with `-g`?

**Comment by fanghuaqi** [comment]
It works in Nuclei Studio, see https://doc.nucleisys.com/nuclei_tools/ide/projectrun.html
